services:
  job1:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["python", "src/python/job_type_1.py", "id1"]
    restart: always
    volumes:
      - ./runtime:/app/runtime
      - ./config:/app/config
  job2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["python", "src/python/job_type_1.py", "id2"]
    restart: always
    volumes:
      - ./runtime:/app/runtime
      - ./config:/app/config